In [1]:
import numpy  as  np

In [2]:
# creating  single dimen  array
a=np.array([1,34,5,77,8])

In [3]:
#  another  one D array
b=np.array([44,77,1,88])

In [4]:
a

array([ 1, 34,  5, 77,  8])

In [5]:
b

array([44, 77,  1, 88])

In [6]:
#  creating  2D array
x=np.array([[2,88],[33,8],[55,8],[33,9]])

In [7]:
x

array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

In [8]:
x[0]

array([ 2, 88])

In [9]:
x[0][1]  #  first row  sec column

88

In [10]:
x[2][0]

55

In [11]:
# range of row
x[0:2]

array([[ 2, 88],
       [33,  8]])

In [13]:
x+3

array([[ 5, 91],
       [36, 11],
       [58, 11],
       [36, 12]])

In [14]:
x*2

array([[  4, 176],
       [ 66,  16],
       [110,  16],
       [ 66,  18]])

In [15]:
x**2

array([[   4, 7744],
       [1089,   64],
       [3025,   64],
       [1089,   81]])

In [16]:
x**3

array([[     8, 681472],
       [ 35937,    512],
       [166375,    512],
       [ 35937,    729]])

In [17]:
x

array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

In [19]:
print(x[0][0] , x[3][1])

2 9


In [20]:
x

array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

In [21]:
#  dime
x.shape

(4, 2)

In [24]:
y=x.reshape(2,4)

In [25]:
y

array([[ 2, 88, 33,  8],
       [55,  8, 33,  9]])

In [48]:
z=y[0:,2:]  #  find out columns 

In [49]:
z*4

array([[132,  32],
       [132,  36]])

In [52]:
#  
zr=np.zeros((5,5))

In [53]:
zr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.ones((6,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.full((4,6),6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [58]:
np.ones((4,4),dtype='int32')  #  converting  data type 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [59]:
# maths ops
x

array([[ 2, 88],
       [33,  8],
       [55,  8],
       [33,  9]])

x1=x*2

In [63]:
x1=x*2

In [64]:
x1

array([[  4, 176],
       [ 66,  16],
       [110,  16],
       [ 66,  18]])

In [67]:
#x*x1
np.add(x,x1)

array([[  6, 264],
       [ 99,  24],
       [165,  24],
       [ 99,  27]])